# filepath: /c:/Users/mikes/Documents/STUDY/MLOps/sentiment_analysis/Dockerfile.base
# Use the official Python image from the Docker Hub
FROM python:3.11-slim

# Set the working directory in the container
WORKDIR /app

# Copy the requirements file into the container
COPY requirements.txt .

# Install the dependencies
RUN pip install --no-cache-dir -r requirements.txt
